os: osx
language: node_js
node_js: '8'
script: yarn run build
cache:
  directories:
  - node_modules
  - "$HOME/.cache/yarn"
  - "$HOME/.electron"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: CC2d5RnpoohBW+EHVuNGEIGfhc3lvWZ2lH+cpKPXvsN8Ia7mO8EQQpdGhlp6WmgoRITKBweIH2BX+C+L4gWLnTOJG65mNPGhQbAfCYk0EJV9FiUfYIEhOF3rHMiQsA4MFYjL96KgZeOgEO+4UPIAENDQihO2h2F4dVmZha5MwEKC48rUtbVlqImyFebWuB08OaLLjd5oS+ilHUA4oi+z2pGE/1bHp4/S2WfM1F3wMdavtFdv/WDqT/vH4tzFWSmImizb0amS4Sxfi+q63UdULBYyua0scDBU2FZZDVniN+np9VWrD1XVEEporFUYmyZWfohJtjgPgk0ZAGuV0S4Jww1DYpow7yRbB+CXNh+5jrf7B3Humc6ar6PENxsPGee4Fqk+GFDO0LXRziTPcMd/6AwYG4igrXSdVozydtK5fzhpFo1t04kc0XdKG0O8HQyIKYRXgPiBdV5kj5Omu2Rp42PJOHZ3gu9H1N87lA9C8OZlnED0YmVIrBY6LUzlbtcrcmvZsHXH4PlLxnbAfwO1KAv2OHQvaRDytbcdALlmbN0jGl7M+AU11lcGILpkx09BAKNQvUN8gNLNWyro4FD9ZMwP9A/BZcd8SkmEj8VVQt3ivdeXPdnvQ9B/QF5mMn40SssxkAQi8/nQeItEKCREE8WylJy7cY3Q70+iQfYRBxM=
  file: "./Glitch.dmg"
  on:
    tags: true
notifications:
  email: false
